### ISSUE TITLE
Korrektur Verfasser / Herausgeber in Feld 100 / 700

### ISSUE THREAD

**Issue by thefass** [ubtue/fid#1]
Bezugsissue: https://github.com/ubtue/tuefind/issues/625

**Comment by thefass** [comment]
Zu prüfende Liste mit k10plus PPN:

767792467
832314870
834411997
842640436
846620987
848694015
849739322
853835667
858644827
859559556
860720756
863266398
866969357
867131098
871129523
872655938
873067932
873074955
876505949
892849932
895375737
1000121216
1001212665
100890192X
1011322315
1014949165
1019183802
1020908823
102540954X
1025439953
1036411788
1039960294
1104636506
1104636573
1577617851
1586383892
1628639369
[Liste erledigt. IxTheoKm 20191119]

**Comment by IxTheoKm** [comment]
Erfassungsform vom PICA-Feld 3000 = MARC21 100 geprüft:

In den meisten Fällen wurden im Prinzip mögliche _zwei_ Beziehungskennzeichnungen erfasst (durch GBV-Einspielungen; in den SWB-Daten stand urspr. PICA 3010 = MARC 700).
Anfrage läuft, ob bei Sammelwerks-Herausgebern, die gleichzeitig einzelne Aufsätze beigetragen haben, "$BVerfasserIn" korrekt ist. M.E. nicht!

Korrektur kann in fast allen Titeln erst erfolgen, wenn der K10plus-Blocktest abgeschlossen ist!
Wo nur "Blocktest" steht, muss Feld 3000 zu 3010 korrigiert werden.

767792467	Blocktest
832314870	$BVerfasserIn$4aut$BHerausgeberIn$4edt
834411997	Blocktest
842640436	$BVerfasserIn$4aut$BHerausgeberIn$4edt
846620987	Blocktest
848694015	$BVerfasserIn$4aut$BHerausgeberIn$4edt
849739322	$BVerfasserIn$4aut$BHerausgeberIn$4edt
853835667	Blocktest
858644827	$BVerfasserIn$4aut$BHerausgeberIn$4edt
859559556	Blocktest
860720756	$BVerfasserIn$4aut$BHerausgeberIn$4edt
863266398	$BVerfasserIn$4aut$BHerausgeberIn$4edt
866969357 	Blocktest
867131098	$BVerfasserIn$4aut$BHerausgeberIn$4edt
871129523	$BVerfasserIn$4aut$BHerausgeberIn$4edt
872655938	Blocktest
873067932	Blocktest
873074955	Blocktest
876505949 	Blocktest
892849932	$BVerfasserIn$4aut$BHerausgeberIn$4edt
895375737	Blocktest
1000121216	$BVerfasserIn$4aut$BHerausgeberIn$4edt
1001212665	$BVerfasserIn$4aut$BHerausgeberIn$4edt
100890192X	Trotz Blocktest korrigiert
1011322315	$BVerfasserIn$4aut$BHerausgeberIn$4edt
1014949165	Blocktest; Mailbox (auch an ZRED)
1019183802	Trotz Blocktest korrigiert
1020908823	$BZusammenstellendeR$4com$BHerausgeberIn$4edt
102540954X	$BVerfasserIn$4aut$BHerausgeberIn$4edt
1025439953	Blocktest
1036411788 	Trotz Blocktest korrigiert
1039960294	Am 09.04.2019 korrigiert
1577617851	$BVerfasserIn$4aut$BHerausgeberIn$4edt
1586383892	$BVerfasserIn$4aut$BHerausgeberIn$4edt
1628639369	$BVerfasserIn$4aut$BHerausgeberIn$4edt

Korrekt: 
$BVerfasserIn$4aut$BHerausgeberIn$4edt$BKommentarverfasserIn$4wac Verfasser wird korrekt angezeigt!
1104636506
1104636573

[Liste erledigt. IxTheoKm 20191119]

**Comment by ruschein** [comment]
Habe jetzt auch auf andere unerlaubte Autorentypen geprüft und folgende Datensätze indentifiziert:

882657585: trl
1031170855: trl

**Comment by IxTheoKm** [comment]
Die Kombination bei 882657585 und 1031170855 ist erlaubt: die in der Tabelle von ubtue/tuefind#625 aufgeführten Beziehungskennzeichen - und nur diese - stehen in Feld 100 an erster Position. 
An zweiter Position dürfen aber alle anderen Beziehungskennzeichen stehen. Auch die von Feld 700.

**Comment by IxTheoKm** [comment]
Im Gegensatz zu den beiden Fällen 882657585 und 1031170855, bei denen die beiden Beziehungskennzeichen korrekt erfasst sind, ist lt. Rücksprache die Erfassung $BVerfasserIn$4aut$BHerausgeberIn$4edt in der o.g. Liste _nicht_ korrekt:

Sammelwerks-Herausgebern, die gleichzeitig einzelne Aufsätze beigetragen haben, müssen beim Sammelwerk in 3010=700 erfasst werden nur mit "$BHerausgeberIn$4edt", da sich die Funktion "VerfasserIn" nur auf den Aufsatz, nicht auf das Sammelwerk bezieht.

Die Titel der o.g. Liste müssen also korrigiert werden, sobald das wieder möglich ist.

**Comment by ruschein** [comment]
Wir haben jetzt in der MARC-Pipeline eine Phase, die uns benachrichtigt wenn die Art des ersten "Verfassers" im 100er Feld nicht stimmt.  Heute wurde folgende Liste erzeugt:

767792467
824397428
834411997
834426110
846620987
853835667
859559556
866969357
872655938
873067932
873074955
876505949
883625733
895375737
100890192X
1014949165
1015936792
1019183802
1025439953
1036411788
1039960294
1327706857
1582506426
1649637217
846171031
77237497X
837958903
873233484
877318476
880568550
1020083123
1039245846
[Liste erledigt. IxTheoKm 20191119]

**Comment by IxTheoKm** [comment]
Wegen "Blocktest" Bereinigung der Titel frühestens ab 13. Mai 2019 möglich

**Comment by IxTheoKm** [comment]
Listen wurden durchgesehen, Datensätze ggf. korrigiert
