### ISSUE TITLE
Fehler im 936l Feld (Jahr)

### ISSUE THREAD

**Issue by ruschein** [ubtue/fid#4]
[936j.txt](https://github.com/ubtue/fid/files/3111157/936j.txt)

Beim Import auf Ptah fanden wir 173 Datensätze bei denen im 936j Feld keine Jahreszahlen sondern Schlagworte stehen.  Wior bitten um eine Korrektur.

**Comment by IxTheoKm** [comment]
Gibt es eine PPN-Liste oder eine Suchanfrage, mit der ich die Sätze finden kann?

**Comment by IxTheoKm** [comment]
Ich finde in den Stichproben im K10plus keine Felder mit 936j.
Es sind meist Datensätze mit dem Code "Blocktest", d.h. da findet noch ein Match & Merge der Normsätze statt. Evtl. sind die Sätze mittlerweile maschinell korrigiert?

**Comment by IxTheoKm** [comment]
Ich glaube, ich habe Ihr Problem gefunden. Beispiel PPN 1025056728
Ich vermute, Sie meinen folgende Fälle:

936 bk$a24.62$jMusiktheater$jTheatermusik$0(DE-627)106422081

Daran kann ich nichts ändern, da es sich um Basisklassifikationen handelt. Die sind in PICA korrekt erfasst.

Wenn alle genannten PPNs so aussehen, darf $j in **936 bk** (=Basisklassifikation) nicht als Jahr für Bandangaben berücksichtigt werden.

**Comment by IxTheoKm** [comment]
Hier die Export-Tabelle aus dem K10plus-Wiki:
![936j](https://user-images.githubusercontent.com/17004223/56895310-0a74c780-6a89-11e9-95d4-0fed65726a9c.JPG)

**Comment by ruschein** [comment]
@IxTheoKm Welches Feld sollen wir dann für die Jahresangabe verwenden?

**Comment by IxTheoKm** [comment]
Zu welchem Zweck brauchen Sie eine Jahresangabe? Meinen Sie die Jahresangaben von Aufsätzen in der Band-, Jahrgangs-, Heft- und Seitenzählung?

Die Basisklassifikation in 936 **bk** $j hat nichts mit der Jahresangaben von Aufsätzen in 936 **uw** $j zu tun. 

In Ihren gelisteten Datensätzen steht das _Erscheinungs_jahr in Feld 264. 
Bsp.: 
PPN 1025056728 aus Ihrer Liste ist ein ganz normales geducktes Buch mit Erscheinungsjahr 2018.
Ich vermute daher, dass diese Fälle gar nicht relevant für Ihre Sortierungsfrage sind.

**Comment by ruschein** [comment]
@IxTheoKm Ich brauche das Erscheinungsjahr und hole es mir jetzt immer aus 008.  Falls Sie wieder eine Email mit Beschwerden über 936 bk $j bekommen, vermerken Sie es bitte in diesem Issue und ich werde mich darum kümmern.

**Comment by IxTheoKm** [comment]
@ruschein Das verstehe ich jetzt nicht: dieses Issue haben Sie doch selber aufgemacht mit dem Hinweis, dass in 173 Fällen "im 936j Feld keine Jahreszahlen sondern Schlagworte" stehen.

Ich habe keine Email-Beschwerde über 936 bk $j bekommen, sondern lediglich darauf hingewiesen, dass in den Fällen der Liste, die in diesem Feld den Indikator "bk" enthalten, _korrekterweise_ keine Jahreszahlen stehen, sondern die Basisklassifikation, die anders behandelt werden muss. Dafür habe ich ein neues Issue 886 aufgemacht. 

936 $j (ohne Indikator bk) ist kein Erscheinungsjahr, sondern das Berichtsjahr bei den Bandangaben eines unselbständigen Werks, also z.B. ein Aufsatz in Band 50. **2019**, Heft 1

**Comment by IxTheoKm** [comment]
@ruschein Kann dieses Issue geschlossen werden?
Wenn in der Liste 936j.txt _überall_ nur 936 **bk** $j und nicht nur 936 $j steht, ist das korrekt und nicht für die Sortierung nach Jahr relevant. Dann muss ich nichts mehr korrigieren.
