### ISSUE TITLE
Fehlende Schlagwörter in RelBib

### ISSUE THREAD

**Issue by ghost** [ubtue/fid#8]
Schlagwörter wurden nicht übernommen, obwohl sie in WinIBW vorhanden sind. 
Siehe ppn 1570617538
**WinIBW** 
![grafik](https://user-images.githubusercontent.com/16898788/75999766-01535300-5f03-11ea-8ea6-456eef6a8d2d.png)

**In RelBib**

![grafik](https://user-images.githubusercontent.com/16898788/75999824-1334f600-5f03-11ea-9ed2-0be396783081.png)

Woran kann dies liegen?

**Comment by IxTheoKm** [comment]
Der Datensatz hat im IxTheo/RelBib den Stand 08.03.2018. Im K10plus wurde der Titel- und Lokalsatz zuletzt am 19.02.2020 von uns korrigiert. Die Korrektur ist nicht angekommen.

**Comment by IxTheoKm** [comment]
Issue im falschen Ordner!
Muss in https://github.com/ubtue/tuefind/issues abgelegt werden!
